// Generated by CoffeeScript 1.6.3
(function() {
  angular.module('swUtils').directive('swFocus', function($timeout, $parse) {
    return {
      restrict: 'A',
      link: function(scope, element, attrs) {
        var model;
        model = $parse(attrs.swFocus);
        scope.$watch(model, function(value) {
          if (value === true) {
            return $timeout(function() {
              return element.focus();
            });
          }
        });
        return element.bind('blur', function() {
          return scope.$apply(model.assign(scope, false));
        });
      }
    };
  }).directive('swLoading', function() {
    return {
      restrict: 'A',
      scope: false,
      link: function(scope, element, attrs) {
        var loadingLayer;
        loadingLayer = $('<div class="loading"></div>').appendTo(element);
        $(element).addClass('sw-loading-container');
        return scope.$watch(attrs.swLoading, function(value) {
          return loadingLayer.toggle(value);
        });
      }
    };
  }).directive('swSelectOnClick', function() {
    return {
      restrict: 'A',
      link: function(scope, element, attrs) {
        return element.on('click', function() {
          return this.select();
        });
      }
    };
  });

}).call(this);
