// Generated by CoffeeScript 1.6.3
(function() {
  angular.module('swUtils').service('swTitle', function() {
    var titleBase, titleEnd, titleStart;
    titleBase = '';
    titleStart = '';
    titleEnd = '';
    this.setTitleBase = function(value) {
      return titleBase = value;
    };
    this.setTitleStart = function(value) {
      return titleStart = value;
    };
    this.setTitleEnd = function(value) {
      return titleEnd = value;
    };
    this.getTitle = function() {
      return "" + titleStart + " " + titleBase + " " + titleEnd;
    };
  }).service('swHttpHelper', function($http) {
    var _this = this;
    this.encodeQueryData = function(data) {
      var d, el, ret, _i, _len, _ref;
      ret = [];
      for (d in data) {
        if (data[d] instanceof Array) {
          _ref = data[d];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            el = _ref[_i];
            ret.push(encodeURIComponent(d) + "=" + encodeURIComponent(el));
          }
        } else {
          ret.push(encodeURIComponent(d) + "=" + encodeURIComponent(data[d]));
        }
      }
      return ret.join("&");
    };
    this.get = function(url, params) {
      var encodeParams, urlWithParams;
      encodeParams = _this.encodeQueryData(params);
      urlWithParams = "" + url + "?" + encodeParams;
      return $http.get(urlWithParams);
    };
    this.post = function(url, params) {
      var encodedParams;
      encodedParams = void 0;
      if (params) {
        encodedParams = $.param(params);
      }
      return $http.post(url, encodedParams);
    };
    this.postJson = function(url, object) {
      return $http.post(url, object);
    };
  });

}).call(this);
